trigger:
 - main

pool:
 vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python312:
      python.version: '3.12'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install setuptools
    python -m pip install .
  displayName: 'Install dependencies'

- script: |
    python -m pip install -r tests/requirements.txt
    python -m pip install coverage==7.7.1
    python -m coverage run --branch -m pytest
  displayName: 'Run tests with coverage'

- script: |
    python -m coverage json
  displayName: 'Generate coverage report'
