name: CI OPC UA SWT

on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r tests/requirements.txt
    - name: Test with pytest
      run: |
        pwd
        ls -a
        pytest
      working-directory: ./
